### ISSUE TITLE
help more options to add 

### ISSUE THREAD

**Issue by rdo3546** [davrob01/AmazonBestSellerBooksScraper#5]
please send me your info to contact you i need your help thank you

**Comment by davrob01** [comment]
Hello,

Please send to this email:

drobsoftware@gmail.com

You can send me an email with more details.

Thank you

**Comment by rdo3546** [comment]
i sent an email thank you

**Comment by davrob01** [comment]
I have updated the app. Edition and image URL are included now.

https://github.com/davrob01/AmazonBestSellerBooksScraper/releases/tag/v1.1

**Comment by JustinGardiner** [comment]
Another feature that I think a lot of people would be interested in is the overall BSR

**Comment by JustinGardiner** [comment]
After actually looking at your code, I suppose it'd be quite a lot to add the overall BSR. I didn't realize that you are getting the ISBN from the URL (and thus actually getting the ASIN for things like audiobooks) and that you aren't actually going to the product page (which is where you'd have to go to get the overall BSR).

**Comment by davrob01** [comment]
Right. Going to each product page could be a future enhancement. And it can be an optional setting/switch. The app would take longer to run but it would be worthwhile since some people are interested in the other book information. However, it is a also feature that may be subjected to more maintenance, depending on how often Amazon changes the html structure on the product pages (something to keep in mind, at least).

Anyway, it is not likely I personally will have time to work on this feature any time soon though, but anybody is welcome to make a contribution. Thank you
